---
title: Moss
email: team@mossworkspace.com
description: A workflow tool as fluid as creativity itself, Moss clarifies the inherently
  messy creative process by consolidating assets and inspiration into a single visual
  workspace.
baseurl: "/landing-page"
url: ''
twitter_username: jekyllrb
github_username: jekyll
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
tagline: Where ideas grow
header:
  logo: "/uploads/moss_logo.png"
  weather: false
  weather_location: Brooklyn, NY
  button: "✍  Join the waitlist"
  logo_light: "/uploads/moss-wordmark-small-white_rgb.png"
footer:
  logo: "/uploads/moss-icon-small__rgb.svg"
  legal: |-
    © 2021
    Moss workspace, inc.
  links:
  - text: Email us
    url: mailto:team@mossworkspace.com
    open_in_new_tab: false
  social:
  - icon: Twitter
    url: https://twitter.com/mossworkspace
  - icon: Instagram
    url: https://www.instagram.com/mossworkspace/
privacy:
  cookie_prompt: This site uses cookies. You can manage your preferences <a href="{{
    '/privacy' | relative_url }}">here</a>.
  privacy_policy: |-
    Vivamus tempor felis mollis condimentum dignissim. Proin fringilla molestie nisl sit amet mollis. Vivamus nibh velit, molestie vel mi eget, fermentum vulputate leo. Praesent neque est, posuere ac neque vitae, maximus scelerisque neque. Pellentesque sed nisi sed nisi tristique ornare quis nec sapien. Fusce feugiat odio ut interdum lobortis. Aenean vitae hendrerit nibh, quis tincidunt metus. Cras nibh risus, eleifend vitae metus a, aliquet elementum nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum dictum tortor, tempor malesuada risus congue id. Integer mauris leo, imperdiet quis aliquam eget, pharetra venenatis nunc. Donec et erat ut elit finibus mollis. Vivamus aliquam arcu a porta porta. Morbi scelerisque orci nulla, id varius urna pretium sit amet. Curabitur tristique nisi vitae interdum dictum.

    Vivamus tempor felis mollis condimentum dignissim. Proin fringilla molestie nisl sit amet mollis. Vivamus nibh velit, molestie vel mi eget, fermentum vulputate leo. Praesent neque est, posuere ac neque vitae, maximus scelerisque neque. Pellentesque sed nisi sed nisi tristique ornare quis nec sapien. Fusce feugiat odio ut interdum lobortis. Aenean vitae hendrerit nibh, quis tincidunt metus. Cras nibh risus, eleifend vitae metus a, aliquet elementum nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum dictum tortor, tempor malesuada risus congue id. Integer mauris leo, imperdiet quis aliquam eget, pharetra venenatis nunc. Donec et erat ut elit finibus mollis. Vivamus aliquam arcu a porta porta. Morbi scelerisque orci nulla, id varius urna pretium sit amet. Curabitur tristique nisi vitae interdum dictum.
