---
title: Moss
email: team@mossworkspace.com
description: A workflow tool as fluid as creativity itself, Moss clarifies the inherently
  messy creative process by consolidating assets and inspiration into a single visual
  workspace.
baseurl: https://mossworkspace.com
url: https://mossworkspace.com
twitter_username: jekyllrb
github_username: jekyll
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
header_settings:
  weather: true
  logo: "/uploads/moss-icon-small__rgb.svg"
  weather_location: Brooklyn, NY
  button: "✍️  Sign up"
tagline: Where ideas grow
footer:
  logo: "/uploads/moss-icon-small__rgb.svg"
  legal: |-
    © 2021
    Moss workspace, inc.
    All rights reserved
  links:
  - text: Privacy Policy
    url: https://www.notion.so/Privacy-a27b700b29334cf4a8984039f3595879
    open_in_new_tab: true
    social_icon: false
  - text: Instagram
    url: https://www.instagram.com/mossworkspace/
    open_in_new_tab: true
    social_icon: true
  - text: Twitter
    url: https://twitter.com/mossworkspace
    open_in_new_tab: true
    social_icon: true
