---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Settings
- type: document
  path: _config.yml
  label: Info & navigation
- type: heading
  label: Pages
- type: document
  path: workspace.markdown
  label: Workspace
- type: document
  path: thesis.markdown
  label: Thesis
- type: document
  path: company.md
  label: Company
- type: jekyll-pages
  label: All pages
  create: documents
  new_doc_ext: markdown
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
