---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: The name of your site
- name: tagline
  type: text
  config:
    required: false
  label: Tagline
  description: Enter a short tagline for your site
- type: textarea
  name: description
  label: Description
  description: What's your site for?
- name: thumbnail_image
  type: file
  config:
    maxSize: 64
  label: Thumbnail image
  description: Choose an image to use for the site's thumbnail on social media.
- type: text
  name: email
  label: Email
  description: A good contact email
- type: text
  name: baseurl
  label: Base URL
  description: 'The base URL of your site (ex: /blog)'
- type: text
  name: url
  label: URL
  description: 'The URL of your site (ex: mossworkspace.com)'
- name: sign_up_field
  type: field_group
  config: {}
  fields:
  - name: prompt
    type: text
    config:
      required: false
    label: Prompt
    description: Placeholder text for the field
  - name: button_text
    type: text
    config:
      required: false
    label: Button text
    description: Text for the button
  label: Sign up field
  description: Settings for the sign up field used across the site
- name: header
  type: field_group
  config: {}
  fields:
  - name: logo
    type: file
    config:
      maxSize: 64
    label: Logo
    description: Choose a logo file
  - name: logo_light
    type: file
    config:
      maxSize: 64
    label: Logo light
    description: Choose a light logo for dark mode
  - name: navigation
    type: field_group_list
    fields:
    - name: icon
      type: file
      config:
        maxSize: 64
      label: Icon
      description: Icon for the navigation link
    - name: text
      type: text
      config:
        required: false
      label: Text
      description: Text for the navigation link
    - name: url
      type: text
      config:
        required: false
      label: URL
      description: URL for the navigation item
    config:
      min: 
      max: 
      labelField: 
    label: Navigation
    description: Pages to navigate to
  - name: buttons
    type: field_group_list
    fields:
    - name: waitlist_button
      type: boolean
      label: Waitlist button
      description: Toggle whether or not this is a waitlist button (scrolls to nearest
        waitlist entry)
    - name: text
      type: text
      config:
        required: false
      label: Text
      description: Text for the button
    - name: url
      type: text
      config:
        required: false
      label: URL
      description: URL for the button
      showOnly:
        field: waitlist_button
    config:
      min: 
      max: 
      labelField: 
    label: Buttons
    description: Additional nav buttons (sign in, waitlist, etc.)
  - name: menu_icon
    type: file
    config:
      maxSize: 64
    label: Menu icon
    description: Choose an image to use as the hamburger menu icon on mobile.
  - name: menu_closed_icon
    type: file
    config:
      maxSize: 64
    label: Menu closed icon
    description: Choose an image to use as the close ( x ) menu icon on mobile.
  label: Header
  description: Choose how the site-wide header displays
- name: footer
  type: field_group
  config: {}
  fields:
  - name: illustrations
    type: image_gallery
    config: {}
    label: Illustrations
    description: Choose illustrations to be randomly shown in the footer.
  - name: link_sections
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: false
      label: Name
      description: Section name
    - name: links
      type: field_group_list
      fields:
      - name: icon
        type: file
        config:
          maxSize: 64
        label: Icon
        description: Icon for the link, ideally 24x24
      - name: text
        type: text
        config:
          required: false
        label: Text
        description: Text for the link
      - name: url
        type: text
        config:
          required: false
        label: URL
        description: URL for the link
      - name: open_in_new_tab
        type: boolean
        label: Open in new tab
        description: Toggle whether or not to open in a new tab
      config:
        min: 
        max: 
        labelField: 
      label: Links
      description: List of links for the section
    config:
      min: 
      max: 
      labelField: 
    label: Link sections
    description: Columns of links for the footer
  label: Footer
  description: Choose how the site-wide footer displays
- name: privacy
  type: field_group
  config: {}
  fields:
  - name: cookie_prompt
    type: text
    config:
      required: false
    label: Cookie prompt
    description: Enter the cookie prompt message
  - name: privacy_policy
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Privacy policy
    description: Enter your privacy policy
  label: Privacy
  description: Settings for privacy &amp; cookies
pages:
- _config.yml
