---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: The name of your site
- name: tagline
  type: text
  config:
    required: false
  label: Tagline
  description: Enter a short tagline for your site
- type: textarea
  name: description
  label: Description
  description: What's your site for?
- name: thumbnail_image
  type: file
  config:
    maxSize: 64
  label: Thumbnail image
  description: Choose an image to use for the site's thumbnail on social media.
- type: text
  name: email
  label: Email
  description: A good contact email
- type: text
  name: baseurl
  label: Base URL
  description: 'The base URL of your site (ex: /blog)'
- type: text
  name: url
  label: URL
  description: 'The URL of your site (ex: mossworkspace.com)'
- type: list
  name: exclude
  label: exclude
  hidden: true
- name: header
  type: field_group
  config: {}
  fields:
  - name: logo
    type: file
    config:
      maxSize: 64
    label: Logo
    description: Choose a logo file
  - name: logo_light
    type: file
    config:
      maxSize: 64
    label: Logo light
    description: Choose a light logo for dark mode
  - name: button
    type: text
    config:
      required: false
    label: Button
    description: Enter the text for the sign up button
  - name: show_jobs_button
    type: boolean
    label: Show jobs button
    description: Toggle to display a jobs button &amp; link
  - name: jobs_button_text
    type: text
    config:
      required: false
    label: Jobs button text
    description: Enter text for the jobs button &amp; link
    showOnly:
      field: show_jobs_button
      value: true
    default: "\U0001F469‍\U0001F4BB Join the team"
  - name: jobs_button_url
    type: text
    config:
      required: false
    label: Jobs button URL
    description: Enter a url for the jobs button to link to
    showOnly:
      field: show_jobs_button
      value: true
  label: Header
  description: Choose how the site-wide header displays
- name: footer
  type: field_group
  config: {}
  fields:
  - name: illustration
    type: file
    config:
      maxSize: 64
    label: Illustration
    description: Choose an illustration file
  - name: link_sections
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: false
      label: Name
      description: Section name
    - name: links
      type: field_group_list
      fields:
      - name: icon
        type: file
        config:
          maxSize: 64
        label: Icon
        description: Icon for the link, ideally 24x24
      - name: text
        type: text
        config:
          required: false
        label: Text
        description: Text for the link
      - name: url
        type: text
        config:
          required: false
        label: URL
        description: URL for the link
      - name: open_in_new_tab
        type: boolean
        label: Open in new tab
        description: Toggle whether or not to open in a new tab
      config:
        min: 
        max: 
        labelField: 
      label: Links
      description: List of links for the section
    config:
      min: 
      max: 
      labelField: 
    label: Link sections
    description: Columns of links for the footer
  label: Footer
  description: Choose how the site-wide footer displays
- name: privacy
  type: field_group
  config: {}
  fields:
  - name: cookie_prompt
    type: text
    config:
      required: false
    label: Cookie prompt
    description: Enter the cookie prompt message
  - name: privacy_policy
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Privacy policy
    description: Enter your privacy policy
  label: Privacy
  description: Settings for privacy &amp; cookies
pages:
- _config.yml
